function [x_sample,M2,M3,mu,w,wM3,W_true,tM3] = genDoc(documents, vocab, topic, tSparsity, dSparsity)
x1_samples= zeros(documents,vocab); x2_samples= zeros(documents,vocab); x3_samples= zeros(documents,vocab); 
x4_samples=x1_samples; x5_samples= x1_samples;
topicDistribution = zeros(documents,topic);
% A_true = rand(vocab, topic); 
% A_true = rdivide(A_true,repmat(sum(A_true,1),vocab,1));
avec = ones(1,vocab)*dSparsity;
A_true = drchrnd(avec, topic);
A_true = A_true';
mu = A_true;
bvec = ones(1,topic)*tSparsity;
w = drchrnd(bvec, 1);
w = w';
%%%
%%% (1b) Generate Synthetic Samples
%%%
for t = 1 : documents
    % generate h for this sample
%     this_h_category = randsample(1:topic,1);
    this_transition_cum = cumsum(w);
    this_h_category = find(this_transition_cum > rand(),1);
    topicDistribution (t,this_h_category) = 1;
    % generate x1 for this sample | h
    this_transition_cum = cumsum(A_true(:,this_h_category));
    this_x_category = find(this_transition_cum > rand(),1);
    x1_samples(t,this_x_category) = 1;
    % generate x2 for this sample | h
    this_x_category = find(this_transition_cum > rand(),1);
    x2_samples(t,this_x_category) = 1;
    % generate x3 for this sample | h
    this_x_category = find(this_transition_cum > rand(),1);
    x3_samples(t,this_x_category) = 1;
    % generate x4 for this sample | h
    this_x_category = find(this_transition_cum > rand(),1);
    x4_samples(t,this_x_category) = 1;
    % generate x5 for this sample | h
    this_x_category = find(this_transition_cum > rand(),1);
    x5_samples(t,this_x_category) = 1;
end

M3 = zeros(vocab,vocab,vocab);
tM3 = M3;
% w = sum(topicDistribution)./sum(sum(topicDistribution));
parfor i = 1:topic
    tM3 = tM3 + w(i)*outprod(A_true(:,i),A_true(:,i),A_true(:,i));
end
[Uw_true, Lw_true, Vw_true] = svd(A_true*diag(w)*A_true');
W_true = Uw_true(:,1:topic)* sqrt(pinv(Lw_true(1:topic,1:topic)));

M2 = zeros(vocab);
parfor i = 1:documents
    M2 = M2 + x1_samples(i,:)'*x2_samples(i,:)+x2_samples(i,:)'*x1_samples(i,:)+...
        x1_samples(i,:)'*x3_samples(i,:)+x3_samples(i,:)'*x1_samples(i,:)+...
        x1_samples(i,:)'*x4_samples(i,:)+x4_samples(i,:)'*x1_samples(i,:)+...
        x1_samples(i,:)'*x5_samples(i,:)+x5_samples(i,:)'*x1_samples(i,:)+...
        x2_samples(i,:)'*x3_samples(i,:)+x3_samples(i,:)'*x2_samples(i,:)+...
        x2_samples(i,:)'*x4_samples(i,:)+x4_samples(i,:)'*x2_samples(i,:)+...
        x2_samples(i,:)'*x5_samples(i,:)+x5_samples(i,:)'*x2_samples(i,:)+...
        x3_samples(i,:)'*x4_samples(i,:)+x4_samples(i,:)'*x3_samples(i,:)+...
        x3_samples(i,:)'*x5_samples(i,:)+x5_samples(i,:)'*x3_samples(i,:)+...
        x4_samples(i,:)'*x5_samples(i,:)+x5_samples(i,:)'*x4_samples(i,:);
    M3 = M3 + outprod(x1_samples(i,:),x2_samples(i,:),x3_samples(i,:)) + outprod(x1_samples(i,:),x3_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x1_samples(i,:),x3_samples(i,:))+outprod(x2_samples(i,:),x3_samples(i,:),x1_samples(i,:))...
        +outprod(x3_samples(i,:),x1_samples(i,:),x2_samples(i,:))+outprod(x3_samples(i,:),x2_samples(i,:),x1_samples(i,:))+...
        outprod(x1_samples(i,:),x2_samples(i,:),x4_samples(i,:)) + outprod(x1_samples(i,:),x4_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x1_samples(i,:),x4_samples(i,:))+outprod(x2_samples(i,:),x4_samples(i,:),x1_samples(i,:))...
        +outprod(x4_samples(i,:),x1_samples(i,:),x2_samples(i,:))+outprod(x4_samples(i,:),x2_samples(i,:),x1_samples(i,:))+...
        outprod(x1_samples(i,:),x2_samples(i,:),x5_samples(i,:)) + outprod(x1_samples(i,:),x5_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x1_samples(i,:),x5_samples(i,:))+outprod(x2_samples(i,:),x5_samples(i,:),x1_samples(i,:))...
        +outprod(x5_samples(i,:),x1_samples(i,:),x2_samples(i,:))+outprod(x5_samples(i,:),x2_samples(i,:),x1_samples(i,:))+...
        outprod(x1_samples(i,:),x4_samples(i,:),x3_samples(i,:)) + outprod(x1_samples(i,:),x3_samples(i,:),x4_samples(i,:))...
        + outprod(x4_samples(i,:),x1_samples(i,:),x3_samples(i,:))+outprod(x4_samples(i,:),x3_samples(i,:),x1_samples(i,:))...
        +outprod(x3_samples(i,:),x1_samples(i,:),x4_samples(i,:))+outprod(x3_samples(i,:),x4_samples(i,:),x1_samples(i,:))+...
        outprod(x1_samples(i,:),x5_samples(i,:),x3_samples(i,:)) + outprod(x1_samples(i,:),x3_samples(i,:),x5_samples(i,:))...
        + outprod(x5_samples(i,:),x1_samples(i,:),x3_samples(i,:))+outprod(x5_samples(i,:),x3_samples(i,:),x1_samples(i,:))...
        +outprod(x3_samples(i,:),x1_samples(i,:),x5_samples(i,:))+outprod(x3_samples(i,:),x5_samples(i,:),x1_samples(i,:))+...
        outprod(x1_samples(i,:),x4_samples(i,:),x5_samples(i,:)) + outprod(x1_samples(i,:),x5_samples(i,:),x4_samples(i,:))...
        + outprod(x4_samples(i,:),x1_samples(i,:),x5_samples(i,:))+outprod(x4_samples(i,:),x5_samples(i,:),x1_samples(i,:))...
        +outprod(x5_samples(i,:),x1_samples(i,:),x4_samples(i,:))+outprod(x5_samples(i,:),x4_samples(i,:),x1_samples(i,:))+...
        outprod(x4_samples(i,:),x2_samples(i,:),x3_samples(i,:)) + outprod(x4_samples(i,:),x3_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x4_samples(i,:),x3_samples(i,:))+outprod(x2_samples(i,:),x3_samples(i,:),x4_samples(i,:))...
        +outprod(x3_samples(i,:),x4_samples(i,:),x2_samples(i,:))+outprod(x3_samples(i,:),x2_samples(i,:),x4_samples(i,:))+...
        outprod(x5_samples(i,:),x2_samples(i,:),x3_samples(i,:)) + outprod(x5_samples(i,:),x3_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x5_samples(i,:),x3_samples(i,:))+outprod(x2_samples(i,:),x3_samples(i,:),x5_samples(i,:))...
        +outprod(x3_samples(i,:),x5_samples(i,:),x2_samples(i,:))+outprod(x3_samples(i,:),x2_samples(i,:),x5_samples(i,:))+...
        outprod(x5_samples(i,:),x2_samples(i,:),x4_samples(i,:)) + outprod(x5_samples(i,:),x4_samples(i,:),x2_samples(i,:))...
        + outprod(x2_samples(i,:),x5_samples(i,:),x4_samples(i,:))+outprod(x2_samples(i,:),x4_samples(i,:),x5_samples(i,:))...
        +outprod(x4_samples(i,:),x5_samples(i,:),x2_samples(i,:))+outprod(x4_samples(i,:),x2_samples(i,:),x5_samples(i,:))+...
        outprod(x5_samples(i,:),x4_samples(i,:),x3_samples(i,:)) + outprod(x5_samples(i,:),x3_samples(i,:),x4_samples(i,:))...
        + outprod(x4_samples(i,:),x5_samples(i,:),x3_samples(i,:))+outprod(x4_samples(i,:),x3_samples(i,:),x5_samples(i,:))...
        +outprod(x3_samples(i,:),x5_samples(i,:),x4_samples(i,:))+outprod(x3_samples(i,:),x4_samples(i,:),x5_samples(i,:));
end
M2 = M2/(20*documents);
M3 = M3/(60*documents);
x_sample(:,:,1) = x1_samples;
x_sample(:,:,2) = x2_samples;
x_sample(:,:,3) = x3_samples;
x_sample(:,:,4) = x4_samples;
x_sample(:,:,5) = x5_samples;

temp3 = tmprod(tM3,W_true',3);
temp2 = tmprod(temp3,W_true',2);
wM3 = tmprod(temp2,W_true',1);